spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa-bookstore
    username: root
    password: P@ssw0rd
    platform: mysql

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "[%thread] %-5level %msg%n"
